django:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - ./:/repo/CIS-627-Web-Database-Services-Development
  links:
    - mysql
mysql:
  image: mysql:8
  expose:
    - "3306"
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=unsecure

